### ISSUE TITLE
Lost connection to MySQL system error: 10054 An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by VladimirAlexiev** [SDM-TIB/SDM-RDFizer#18]
My config is:
```
[default]
main_directory: .

[datasets]
number_of_datasets: 1
output_folder: .
remove_duplicate: no
all_in_one_file: no
name: customer
enrichment: no
dbType: postgres

[dataset1]
name: customer
mapping: ../customer.rml
host: localhost
port: 5432
user: postgres
password: ...
db: ...
```

As you see in #17, it starts working on postgres: `executor.submit(semantify_postgres...`.

After about 50s I get this error:
```
Traceback (most recent call last):
  File "...Python37\lib\site-packages\mysql\connector\network.py", line 246, in recv_plain
    chunk = self.sock.recv(4 - packet_len)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 3423, in <module>
    main()
  File "../SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 3420, in main
    semantify(config_path)
  File "../SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 3306, in semantify
    db = connector.connect(host = host, port = port, user = user, password = password)
  File "...Python37\lib\site-packages\mysql\connector\__init__.py", line 183, in connect
    return MySQLConnection(*args, **kwargs)
  File "...Python37\lib\site-packages\mysql\connector\connection.py", line 100, in __init__
    self.connect(**kwargs)
  File "...Python37\lib\site-packages\mysql\connector\abstracts.py", line 736, in connect
    self._open_connection()
  File "...Python37\lib\site-packages\mysql\connector\connection.py", line 243, in _open_connection
    self._do_handshake()
  File "...Python37\lib\site-packages\mysql\connector\connection.py", line 109, in _do_handshake
    packet = self._socket.recv()
  File "...Python37\lib\site-packages\mysql\connector\network.py", line 275, in recv_plain
    errno=2055, values=(self.get_address(), _strioerror(err)))
mysql.connector.errors.OperationalError: 2055: Lost connection to MySQL server at 'localhost:5432', system error: 10054 An existing connection was forcibly closed by the remote host
```

Does this mean you forgot somewhere that the database is postgres not MySQL? Or these packages work on postgres, despite their name?

**Comment by VladimirAlexiev** [comment]
- You got 3 spots that do `psycopg2.connect`. But you got 5 spots that do `connector.connect` where `connector` means MySQL.
- Is it really necessary to do database opening from so many places?
- also see #18

**Comment by eiglesias34** [comment]
We require these many for different operations. For example, a join between a csv source and mysql source.

**Comment by eiglesias34** [comment]
I found the problem. There was a call to a MySQL database when it should have been a call to Postgres database. Please test it out.
