### ISSUE TITLE
TypeError: Can't convert 'list' object to str implicitly

### ISSUE THREAD

**Issue by daniel-dona** [SDM-TIB/SDM-RDFizer#27]
**Describe the bug**
```
Semantifying gtfs...
Traceback (most recent call last):
  File "/repository/SDM-RDFizer/rdfizer/run_rdfizer.py", line 3, in <module>
    semantify(str(sys.argv[1]))
  File "/repository/SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 3174, in semantify
    number_triple += executor.submit(semantify_file, triples_map, triples_map_list, ",", output_file_descriptor, wr, config[dataset_i]["name"], data).result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/repository/SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 1954, in semantify_file
    if triples_map_element.triples_map_id + "_" + predicate_object_map.object_map.child not in join_table:
TypeError: Can't convert 'list' object to str implicitly
```

**To Reproduce**
Steps to reproduce the behavior (and resources):
1. Clone last version from git
2. Install necesary dependencies from requirements.txt
3. Write config file:
```
[default]
main_directory: /tmp/output/rdf

[datasets]
number_of_datasets: 1
output_folder: ${default:main_directory}/graph
name: gtfs
remove_duplicate: no
all_in_one_file: no
enrichment: yes

[dataset1]
name: gtfs
mapping: /tmp/output/mappings/mapping_csv.nt
```
4. Run SDM-RDFizer:
`python3.5 /repository/SDM-RDFizer/rdfizer/run_rdfizer.py /repository/gtfs-bench/semantify/csv.conf`

**Expected behavior**
Output a RDF knowledge graph

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
GTFS-Bench Docker Image

**Comment by eiglesias34** [comment]
I fixed the problem. Please test it out and tell if you still are having the same problem.

**Comment by dachafra** [comment]
solved
