### ISSUE TITLE
Error with XML source  files 

### ISSUE THREAD

**Issue by FrankBorrero** [SDM-TIB/SDM-RDFizer#34]
Hi, Using SDM-RDFIzer  with XML files, and  im geting this two error:

**error 1**
Traceback (most recent call last):
  File "/home/fborrero/SDM-RDFizer/SDM-RDFizer/rdfizer/run_rdfizer.py", line 3, in <module>
    semantify(str(sys.argv[1]))
  File "/home/fborrero/SDM-RDFizer/SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 3648, in semantify
    number_triple += executor.submit(semantify_xml, triples_map, triples_map_list, output_file_descriptor, wr, config[dataset_i]["name"]).result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/fborrero/SDM-RDFizer/SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 854, in semantify_xml
    object = "<" + string_substitution_xml(predicate_object_map.object_map.value, "{(.+?)}", row, "object") + ">"
NameError: name 'row' is not defined

**error 2**

Semantifying KGCase2-2david.nt...
Traceback (most recent call last):
  File "/home/fborrero/SDM-RDFizer/SDM-RDFizer/rdfizer/run_rdfizer.py", line 3, in <module>
    semantify(str(sys.argv[1]))
  File "/home/fborrero/SDM-RDFizer/SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 3648, in semantify
    number_triple += executor.submit(semantify_xml, triples_map, triples_map_list, output_file_descriptor, wr, config[dataset_i]["name"]).result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/fborrero/SDM-RDFizer/SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 860, in semantify_xml
    object = string_substitution_xml(predicate_object_map.object_map.value, ".+", child, "object")
  File "/home/fborrero/SDM-RDFizer/SDM-RDFizer/rdfizer/rdfizer/functions.py", line 157, in string_substitution_xml
    if re.search("^[\s|\t]*$", row.find(match).text) is None:
AttributeError: 'NoneType' object has no attribute 'text'

The data sourcefiles, and the mapping files were use  with  RMLmapper, and RockterRML and no problems were presented at the moment of generating the graph. 

This let me assume that there is not any problem with source files or the mapping files as it worked with the other RDFizers.
Im attaching the source files used, also the mapping files and the configfile.ini for reproducibility.

[Xml.zip](https://github.com/SDM-TIB/SDM-RDFizer/files/5261149/Xml.zip)

**Comment by eiglesias34** [comment]
I finished updating the SDM-RDFizer. I executed the data that was given and it was able process the data. Please confirm, so that we can close the issue.

**Comment by FrankBorrero** [comment]
Execution was done without errors. Thanks.
