### ISSUE TITLE
Error when using different source files

### ISSUE THREAD

**Issue by FrankBorrero** [SDM-TIB/SDM-RDFizer#35]
Hi, when I'm using a mapping file the SDM tool, Im getting following error.  I have to remark that mapping file was used with RocketRML and I did not have any problems. So its  not about the mapping file. Attaching the source files (different sources), config file , and the mapping.

Thanks

Semantifying KGCase04.nt...

TM: http://mapping.example.com/map_calendar_date_rules_0

TM: http://mapping.example.com/map_calendar_rules_0

TM: http://mapping.example.com/map_trips_0

TM: http://mapping.example.com/map_shapes_0

TM: http://mapping.example.com/map_services2_0

TM: http://mapping.example.com/map_feed_0

TM: http://mapping.example.com/map_services1_0

TM: http://mapping.example.com/map_stoptimes_0
Traceback (most recent call last):
File "/home/fborrero/env/lib/python3.8/site-packages/mysql/connector/abstracts.py", line 309, in config
self._port = int(config['port'])
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/fborrero/SDM-RDFizer/SDM-RDFizer/rdfizer/run_rdfizer.py", line 3, in
semantify(str(sys.argv[1]))
File "/home/fborrero/SDM-RDFizer/SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 3643, in semantify
number_triple += executor.submit(semantify_file, triples_map, triples_map_list, ",", output_file_descriptor, wr, config[dataset_i]["name"], data).result()
File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
return self.__get_result()
File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
raise self._exception
File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/fborrero/SDM-RDFizer/SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 2055, in semantify_file
db = connector.connect(host=host, port=port, user=user, password=password)
File "/home/fborrero/env/lib/python3.8/site-packages/mysql/connector/init.py", line 183, in connect
return MySQLConnection(*args, **kwargs)
File "/home/fborrero/env/lib/python3.8/site-packages/mysql/connector/connection.py", line 100, in init
self.connect(**kwargs)
File "/home/fborrero/env/lib/python3.8/site-packages/mysql/connector/abstracts.py", line 733, in connect
self.config(**kwargs)
File "/home/fborrero/env/lib/python3.8/site-packages/mysql/connector/abstracts.py", line 314, in config
raise errors.InterfaceError(
mysql.connector.errors.InterfaceError: TCP/IP port number should be an integer

[Mapping-config.zip](https://github.com/SDM-TIB/SDM-RDFizer/files/5276872/Mapping-config.zip)

[source_files_custom.zip](https://github.com/SDM-TIB/SDM-RDFizer/files/5276868/source_files_custom.zip)

**Comment by eiglesias34** [comment]
Could you also provide the MySQL data used and the mapping as well?

**Comment by FrankBorrero** [comment]
Hi. Im not using any Mysql data.  This is distribution from source files
AGENCY TM: JSON
 CALENDAR_DATES TM: XML
CALENDAR TM: CSV
FEED_INFO TM: JSON
 FREQUENCIES TM: XML
 ROUTES TM: CSV
STOPS TM: XML
TRIPS TM: JSON
The mapping file was attached.  Mapping-config.zip, it contains The mapping and config file used. Also im attaching the sources files.

**Comment by eiglesias34** [comment]
I updated the SDM-RDFizer. I ran it multiple times to make sure that it works and that it returned the same result each time. Please confirm, so that we can close this issue.

**Comment by FrankBorrero** [comment]
It was executed agai, and it ran sucesfully. Thanks. Will close the issue now.
