### ISSUE TITLE
error transforming a json file

### ISSUE THREAD

**Issue by fpriyatna** [SDM-TIB/SDM-RDFizer#46]
I encountered an error while transforming a JSON file. Unfortunately, I am not able to share the RML file nor the JSON file, but here is the error trace. The same mapping file can be executed with RMLMapper.

```
Semantifying joinCondition...
Traceback (most recent call last):
  File "/app/rdfizer/run_rdfizer.py", line 3, in <module>
    semantify(str(sys.argv[1]))
  File "/app/rdfizer/rdfizer/semantify.py", line 3899, in semantify
    number_triple += executor.submit(semantify_json, triples_map, triples_map_list, ",",output_file_descriptor, wr, config[dataset_i]["name"], data).result()
  File "/usr/local/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/rdfizer/rdfizer/semantify.py", line 1595, in semantify_json
    object = string_substitution_json(predicate_object_map.object_map.value, ".+", data, "object",ignore)
  File "/app/rdfizer/rdfizer/functions.py", line 101, in string_substitution_json
    if (type(value).__name__) == "int":
UnboundLocalError: local variable 'value' referenced before assignment
```

**Comment by eiglesias34** [comment]
Hello,

I added the missing value assignment. Please confirm if the problem is fixed.

Thank you for using the SDM-RDFizer.

**Comment by fpriyatna** [comment]
Thank you for your quick response!

I tried with the new version but now I got another error:
```
Traceback (most recent call last):
  File "/app/rdfizer/run_rdfizer.py", line 3, in <module>
    semantify(str(sys.argv[1]))
  File "/app/rdfizer/rdfizer/semantify.py", line 3899, in semantify
    number_triple += executor.submit(semantify_json, triples_map, triples_map_list, ",",output_file_descriptor, wr, config[dataset_i]["name"], data).result()
  File "/usr/local/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/rdfizer/rdfizer/semantify.py", line 1587, in semantify_json
    object = "<" + string_substitution_json(predicate_object_map.object_map.value, "{(.+?)}", row, "object",ignore) + ">"
NameError: name 'row' is not defined
```

**Comment by eiglesias34** [comment]
I fixed the problem. Please test it out.

**Comment by fpriyatna** [comment]
thank you again.

Here is another problem:
```
Traceback (most recent call last):
  File "/app/rdfizer/run_rdfizer.py", line 3, in <module>
    semantify(str(sys.argv[1]))
  File "/app/rdfizer/rdfizer/semantify.py", line 3899, in semantify
    number_triple += executor.submit(semantify_json, triples_map, triples_map_list, ",",output_file_descriptor, wr, config[dataset_i]["name"], data).result()
  File "/usr/local/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/rdfizer/rdfizer/semantify.py", line 1595, in semantify_json
    object = string_substitution_json(predicate_object_map.object_map.value, ".+", data, "object",ignore)
  File "/app/rdfizer/rdfizer/functions.py", line 95, in string_substitution_json
    value = row[temp[1]]
KeyError: 'title'
```
