### ISSUE TITLE
unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by ArenasGuerreroJulian** [SDM-TIB/SDM-RDFizer#54]
Hi!

I get the following error:

```
Traceback (most recent call last):
  File "run_rdfizer.py", line 3, in <module>
    semantify(str(sys.argv[1]))
  File "/home/julian/GitHub/SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 4277, in semantify
    number_triple += executor.submit(semantify_mysql, row, row_headers, triples_map, triples_map_list, output_file_descriptor, wr, config[dataset_i]["name"], config[dataset_i]["host"], int(config[dataset_i]["port"]), config[dataset_i]["user"], config[dataset_i]["password"],config[dataset_i]["db"]).result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/julian/GitHub/SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 3128, in semantify_mysql
    if child_list_value_array(predicate_object_map.object_map.child,row,row_headers) in join_table[triples_map_element.triples_map_id + "_" + child_list(predicate_object_map.object_map.child)]:
  File "/home/julian/GitHub/SDM-RDFizer/rdfizer/rdfizer/functions.py", line 34, in child_list_value_array
    value += row[row_headers.index(child)] + "_"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

The naive solution that works for me is:

```
	for child in childs:
		if child not in v:
			if row[row_headers.index(child)] != None:
				value += row[row_headers.index(child)] + "_"
```

But check i would check whether that is right.

Best,
Julián

**Comment by eiglesias34** [comment]
Hi,
I added the Nonetype verification.
