### ISSUE TITLE
Bug found, rdfizer fails if the column referenced by a objectMap with the property rr:language is empty

### ISSUE THREAD

**Issue by w0xter** [SDM-TIB/SDM-RDFizer#7]
Hi guys, I  found a bug:

**Data:**

```csv
id,spanish,english
0,coche,car
2,,sandwich
3,bicicleta,

```

**RML:**

```ttl
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix fnml: <http://semweb.mmlab.be/ns/fnml#>.
@prefix fno: <https://w3id.org/function/ontology#>.
@prefix d2rq: <http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#>.
@prefix : <http://mapping.example.com/>.
@prefix ex: <http://example.com/>.

:map_translations_0 rml:logicalSource :source_0.
:source_0 a rml:LogicalSource;
    rml:source "/home/w0xter/Tools/SDM-RDFizer/bugs/lang/data.csv";
    rml:referenceFormulation ql:CSV.
:map_translations_0 a rr:TriplesMap;
    rdfs:label "translations".
:s_0 a rr:SubjectMap.
:map_translations_0 rr:subjectMap :s_0.
:s_0 rr:template "http://example.com/translation/{id}".
:pom_0 a rr:PredicateObjectMap.
:map_translations_0 rr:predicateObjectMap :pom_0.
:pm_0 a rr:PredicateMap.
:pom_0 rr:predicateMap :pm_0.
:pm_0 rr:constant ex:english.
:pom_0 rr:objectMap :om_0.
:om_0 a rr:ObjectMap;
    rml:reference "english";
    rr:termType rr:Literal;
    rr:language "en".
:pom_1 a rr:PredicateObjectMap.
:map_translations_0 rr:predicateObjectMap :pom_1.
:pm_1 a rr:PredicateMap.
:pom_1 rr:predicateMap :pm_1.
:pm_1 rr:constant ex:spanish.
:pom_1 rr:objectMap :om_1.
:om_1 a rr:ObjectMap;
    rml:reference "spanish";
    rr:termType rr:Literal;
    rr:language "es".

```

**Output:**

```txt
Semantifying result...
Traceback (most recent call last):
  File "run_rdfizer.py", line 3, in <module>
    semantify(str(sys.argv[1]))
  File "/home/w0xter/Tools/SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 3037, in semantify
    number_triple += executor.submit(semantify_file, triples_map, triples_map_list, ",", output_file_descriptor, wr, config[dataset_i]["name"], data).result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/w0xter/Tools/SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 1794, in semantify_file
    object += "@es"
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

```

I think it is easy to fix, just check if the column value is empty before concatenating.

**Comment by w0xter** [comment]
It's fixed, thanks!!
