### ISSUE TITLE
SDM-RDFizer crashes when semantifying file

### ISSUE THREAD

**Issue by DylanVanAssche** [SDM-TIB/SDM-RDFizer#93]
**Describe the bug**
While testing the 4.6.3 release for #92 , I noticed that the SDM-RDFizer now crashes when semantifying a file:

```
..Traceback (most recent call last):
File "//sdm-rdfizer/rdfizer/run_rdfizer.py", line 3, in <module>
semantify(str(sys.argv[1]))
File "/sdm-rdfizer/rdfizer/rdfizer/semantify.py", line 4442, in semantify
Semantifying sdmrdfizer_file...
number_triple += executor.submit(semantify_file, sorted_sources[source_type][source][triples_map], triples_map_list, ",", output_file_descriptor, config[dataset_i]["name"], data).result()
File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
return self.__get_result()
File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
raise self._exception
File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
TypeError: semantify_file() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
File "//sdm-rdfizer/rdfizer/run_rdfizer.py", line 3, in <module>
semantify(str(sys.argv[1]))
File "/sdm-rdfizer/rdfizer/rdfizer/semantify.py", line 4442, in semantify
Semantifying sdmrdfizer_file...
number_triple += executor.submit(semantify_file, sorted_sources[source_type][source][triples_map], triples_map_list, ",", output_file_descriptor, config[dataset_i]["name"], data).result()
File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
return self.__get_result()
File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
raise self._exception
File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
TypeError: semantify_file() takes 5 positional arguments but 6 were given
```

**To Reproduce**
Steps to reproduce the behavior (and resources):
1. Download SDM-RDFizer 4.6.3
2. Transform a CSV to RDF with the SDM-RDFizer

**Expected behavior**

The SDM-RDFizer does not crash

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by DylanVanAssche** [comment]
[example.zip](https://github.com/SDM-TIB/SDM-RDFizer/files/10015484/example.zip)

**Comment by eiglesias34** [comment]
The new release fixes this problem. I used the example you sent, and everything good.

**Comment by DylanVanAssche** [comment]
@eiglesias34 Thanks a lot Enrique! It all works again in 4.6.3.1!
